export const coaches = [
    {
        "name":"Mr. Renauld",
        "description":"Mr. Renauld is a seasoned veteran of FIRST Robotics and has helped teams compete for 18 years as a mentor. He is also an engineering teacher at St. Paul's School. Prior to St. Paul's, he founded the FIRST robotics team “Ozram” while teaching at Hopkinton High School.",
        "image":"images/members/Renauld.jpg",
    },
    {
        "name": "Dr. Justinvil",
        "description": "While relatively new, Dr. Justinvil has become an integral member of the 1512 team. Dr. Justinvil was a STEAM-Scholar in-Residence at day school Palm Beach Day Academy and is well involved with NGO HaitiFirst inc., to promote education, technology, and health access in Haiti.",
        "image": "images/members/Justinvil.jpg"
    },
    {
        "name": "Mr. Lalancette",
        "description": "Mr. Lalancette is a skilled individual with extensive experience in mechanical engineering and robotics. As a part-time member of our team, he provides valuable insights and helps us tackle complex projects with his hands-on expertise.",
        "image": "images/members/Lalancette.jpg",
    }
];
// MembersList.js
export const students = [
    {
        "name": "Jack",
        "last": "Rubiralta",
        "form": "VI",
        "hometown": "Barcelona",
        "captainType": "Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Tess",
        "last": "Barton",
        "form": "V",
        "hometown": "Northampton, MA",
        "club": true,
        "class": false,
    },
    {
        "name": "Adi",
        "last": "Challagulla",
        "form": "IV",
        "hometown": "Andover, MA",
        "club": true,
        "class": true,
    },
    {
        "name": "Leo",
        "last": "Colinet",
        "form": "IV",
        "hometown": "Candiac, QC",
        "club": true,
        "class": false,
    },
    {
        "name": "Oyinna",
        "last": "Ekeh",
        "form": "IV",
        "hometown": "Lima, OH",
        "club": true,
        "class": false,
    },
    {
        "name": "Tristan",
        "last": "Emerson",
        "form": "V",
        "hometown": "Hong Kong",
        "club": true,
        "class": false,
    },
    {
        "name": "Alex",
        "last": "Gallien",
        "form": "IV",
        "hometown": "Paris, France",
        "club": true,
        "class": false,
    },
    {
        "name": "Tristan",
        "last": "Gonzalez",
        "form": "IV",
        "hometown": "Newark, NJ",
        "club": true,
        "class": false,
    },
    {
        "name": "Liz",
        "last": "Harder",
        "form": "VI",
        "hometown": "Munich, Germany",
        "club": true,
        "class": false,
    },
    {
        "name": "Zamirh",
        "last": "Kawuma",
        "form": "IV",
        "hometown": "Newark, NJ",
        "club": true,
        "class": false,
    },
    {
        "name": "Ella",
        "last": "Kim",
        "form": "VI",
        "hometown": "Hong Kong",
        "captainType": "Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Aaron",
        "last": "Kimiri",
        "form": "IV",
        "hometown": "Haverhill, MA",
        "club": true,
        "class": false,
    },
    {
        "name": "Anna",
        "last": "Liu",
        "form": "VI",
        "hometown": "Atlanta, GA",
        "captainType": "Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Grant",
        "last": "Meyerle",
        "form": "III",
        "hometown": "Ardmore, PA",
        "club": true,
        "class": false,
    },
    {
        "name": "Cyrus",
        "last": "Mohebi",
        "form": "III",
        "hometown": "San Francisco, CA",
        "club": true,
        "class": false,
    },
    {
        "name": "Motoki",
        "last": "Nakajima",
        "form": "IV",
        "hometown": "Tokyo, Japan",
        "club": true,
        "class": true,
    },
    {
        "name": "Clara",
        "last": "Tcherepnin",
        "form": "V",
        "hometown": "Duxbury, MA",
        "captainType": "Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Raya",
        "last": "Yuguchi",
        "form": "V",
        "hometown": "Tokyo, Japan",
        "club": true,
        "class": false,
    },
    {
        "name": "Linus",
        "last": "Krenkel",
        "form": "IV",
        "hometown": "Portland, ME",
        "driver": true,
        "captainType": "King Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Lily",
        "last": "ReId",
        "form": "V",
        "hometown": "Pelham, NY",
        "driver": true,
        "captainType": "Captain",
        "club": false,
        "class": true,
    },
    {
        "name": "Tyler",
        "last": "Wang",
        "form": "VI",
        "hometown": "San Marino, CA",
        "driver": false,
        "club": true,
        "class": false,
    },
    {
        "name": "Kevin",
        "last": "Wu",
        "form": "VI",
        "hometown": "Toronto, Canada",
        "captainType": "School President",
        "club": true,
        "class": false,

    },
    {
        "name": "Maddie",
        "last": "Morse",
        "form": "V",
        "hometown": "Rye, NH",
        "club": false,
        "class": true,
    },
    {
        "name": "Brady",
        "last": "Hall",
        "form": "V",
        "hometown": "Newport, RI",
        "club": false,
        "class": true,
    },
    {
        "name": "Motunrayo",
        "last": "Odukoya",
        "form": "IV",
        "hometown": "Somerset, NJ",
        "club": false,
        "class": true,
    },
    {
        "name": "Finn",
        "last": "Ryan",
        "form": "V",
        "hometown": "Chicago, IL",
        "club": false,
        "class": true,
    },
    {
        "name": "Kyan",
        "last": "Hands",
        "form": "IV",
        "hometown": "Paget, Bermuda",
        "club": false,
        "class": true,
    },
    {
        "name": "Anderson",
        "last": "Brady",
        "form": "V",
        "hometown": "Pinehurst, NC",
        "club": false,
        "class": true,
    },
    {
        "name": "Daniel",
        "last": "Hong",
        "form": "IV",
        "hometown": "Rch Palos Vrd, CA",
        "club": false,
        "class": true,
    },
    {
        "name": "Aarav",
        "last": "Mehta",
        "form": "IV",
        "hometown": "Hopkinton, MA",
        "club": true,
        "class": false,
    },
];
