export const coaches = [
    {
        "name":"Mr. Renuald",
        "description":"Mr. Renauld is a seasoned veteran of First Robotics and has been helping teams compete for 18 years as a mentor. He is also an engineering teacher at St. Paul's School. He was also the founder of the FIRST robotics team “Ozram” while teaching at Hopkinton High School.",
        "image":"images/members/Renauld.jpg",
    },
    {
        "name": "Dr. Justinvil",
        "description": "While relatively new, Dr. Justinvil has became an integral member of the 1512 team. Dr. Justinvil was a STEAM-Scholar in-Residence at a day school, Palm Beach Day Academy, and is very involved with an NGO, HaitiFirst inc., to promote education, technology, and health access In Haiti.",
        "image": "images/members/Justinvil.jpg"
    },
    {
        "name": "Mr. Lalancette",
        "description": "Mr. Lalancette is a new member of the team and is a math teacher at St. Paul's School. He has been helping the team with the programming of the robot and has been a great help to the team.",
        "image": "images/members/Lalancette.jpg",
    }
];
// MembersList.js
export const students = [
    {
        "name": "Jack",
        "last": "Rubiralta Kunze",
        "form": "VI",
        "hometown": "Barcelona",
        "captainType": "Senior Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Tess",
        "last": "Barton",
        "form": "V",
        "hometown": "Northampton, MA",
        "club": true,
        "class": true,
    },
    {
        "name": "Adi",
        "last": "Challagulla",
        "form": "IV",
        "hometown": "Andover, MA",
        "club": true,
        "class": false,
    },
    {
        "name": "Leo",
        "last": "Colinet",
        "form": "IV",
        "hometown": "Candiac, QC",
        "club": true,
        "class": false,
    },
    {
        "name": "Oyinna",
        "last": "Ekeh",
        "form": "IV",
        "hometown": "Lima, OH",
        "club": true,
        "class": false,
    },
    {
        "name": "Tristan",
        "last": "Emerson",
        "form": "V",
        "hometown": "Hong Kong",
        "club": true,
        "class": true,
    },
    {
        "name": "Alex",
        "last": "Gallien",
        "form": "IV",
        "hometown": "Paris, France",
        "club": true,
        "class": false,
    },
    {
        "name": "Tristan",
        "last": "Gonzalez",
        "form": "IV",
        "hometown": "Newark, NJ",
        "club": true,
        "class": false,
    },
    {
        "name": "Liz",
        "last": "Harder",
        "form": "VI",
        "hometown": "Munich, Germany",
        "club": true,
        "class": false,
    },
    {
        "name": "Zamirh",
        "last": "Kawuma",
        "form": "IV",
        "hometown": "Newark, NJ",
        "club": true,
        "class": false,
    },
    {
        "name": "Ella",
        "last": "Kim",
        "form": "VI",
        "hometown": "Hong Kong, HK",
        "captainType": "Senior Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Aaron",
        "last": "Kimiri",
        "form": "IV",
        "hometown": "Haverhill, MA",
        "club": true,
        "class": false,
    },
    {
        "name": "Anna",
        "last": "Liu",
        "form": "VI",
        "hometown": "Atlanta, GA",
        "captainType": "Senior Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Grant",
        "last": "Meyerle",
        "form": "III",
        "hometown": "Ardmore, PA",
        "club": true,
        "class": false,
    },
    {
        "name": "Cyrus",
        "last": "Mohebi",
        "form": "III",
        "hometown": "San Francisco, CA",
        "club": true,
        "class": false,
    },
    {
        "name": "Motoki",
        "last": "Nakajima",
        "form": "IV",
        "hometown": "Tokyo, Japan",
        "club": true,
        "class": false,
    },
    {
        "name": "Clara",
        "last": "Tcherepnin",
        "form": "V",
        "hometown": "Duxbury, MA",
        "captainType": "Junior Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Raya",
        "last": "Yuguchi",
        "form": "V",
        "hometown": "Tokyo, Japan",
        "club": true,
        "class": false,
    },
    {
        "name": "Linus",
        "last": "K",
        "form": "IV",
        "hometown": "Portland, ME",
        "driver": true,
        "captainType": "King Krenkal Captain",
        "club": true,
        "class": false,
    },
    {
        "name": "Lily",
        "last": "R",
        "form": "V",
        "hometown": "Pelham, NY",
        "driver": true,
        "captainType": "Junior Captain",
        "club": false,
        "class": true,
    },
    {
        "name": "Tyler",
        "last": "Wang",
        "form": "VI",
        "hometown": "San Marino, Ca",
        "driver": true,
        "club": true,
        "class": false,
    }
];
