export const coaches = [
    {
        "name":"Mr. Renuald",
        "description":"Mr. Renauld is a seasoned veteran of First Robotics and has been helping teams compete for 18 years as a mentor. He is also an engineering teacher at St. Paul's School. He was also the founder of the FIRST robotics team “Ozram” while teaching at Hopkinton High School.",
        "image":"images/members/Renauld.jpg",
    },
    {
        "name": "Dr. Justinvil",
        "description": "While relatively new, Dr. Justinvil has became an integral member of the 1512 team. Dr. Justinvil was a STEAM-Scholar in-Residence at a day school, Palm Beach Day Academy, and is very involved with an NGO, HaitiFirst inc., to promote education, technology, and health access In Haiti.",
        "image": "images/members/Justinvil.jpg"
    },
    {
        "name": "Mr. Lalancette",
        "description": "Mr. Lalancette is a new member of the team and is a math teacher at St. Paul's School. He has been helping the team with the programming of the robot and has been a great help to the team.",
        "image": "images/members/Lalancette.jpg",
    }
];

export const students = [
    {
        "name":"Henry",
        "last":"A",
        "form":"VI",
        "hometown":"Rangeley, ME",
        "teamCaptain":true,
        "club":true,
        "class":true,
    },
    {
        "name":"Jack",
        "last":"B",
        "form":"VI",
        "hometown":"Brooklyn, NY",
        "teamCaptain":true,
        "driver":true,
        "club":true,
        "class":false,
    },
    {
        "name":"Tyler",
        "last":"W",
        "form":"V",
        "hometown":"Los Angeles, CA",
        "driver":true,
        "club":false,
        "class":true,
    },
    {
        "name":"Brandon",
        "last":"M",
        "form":"VI",
        "hometown":"Somerset, NJ",
        "club":true,
        "class":false,
    },
    {
        "name":"Jack",
        "last":"R",
        "form":"V",
        "hometown":"Barcelona, Spain",
        "club":true,
        "class":false,
    },{
        "name":"Junyi",
        "last":"L",
        "form":"IV",
        "hometown":"Beijing, China",
        "club":true,
        "class":false,
    },{
        "name":"Thomas",
        "last":"A",
        "form":"IV",
        "hometown":"Nashville, TN",
        "club":true,
        "class":false,
    },{
        "name":"Anna",
        "last":"L",
        "form":"V",
        "hometown":"Atlanta, GA",
        "club":true,
        "class":false,
    },
    {
        "name":"Vicky",
        "last":"Z",
        "form":"V",
        "hometown":"Toronto, ON, Canada",
        "club":true,
        "class":false,
    },
    {
        "name":"Ella",
        "last":"K",
        "form":"V",
        "hometown":"Hong Kong, HK",
        "club":true,
        "class":false,
    },
    {
        "name":"Xingguo",
        "last":"D",
        "form":"IV",
        "hometown":"'Global Citizen'",
        "club":true,
        "class":false,
    },
    {
        "name":"Jay",
        "last":"N",
        "form":"IV",
        "hometown":"California",
        "club":false,
        "class":true,
    },
    {
        "name":"Christian",
        "last":"F",
        "form":"IV",
        "hometown":"New York",
        "club":false,
        "class":true,
    },
    {
        "name":"Kristof",
        "last":"L",
        "form":"V",
        "hometown":"San Jose, CA",
        "club":false,
        "class":true,
    },
    {
        "name":"Enzo",
        "last":"L",
        "form":"V",
        "hometown":"Columbia, SC",
        "club":false,
        "class":true,
    },
    {
        "name":"Clifton",
        "last":"W",
        "form":"V",
        "hometown":"Charleston, SC",
        "club":false,
        "class":true,
    },
    {
        "name":"Ali",
        "last":"C",
        "form":"V",
        "hometown":"Concord, NH",
        "club":false,
        "class":true,
    },
    {
        "name":"Addison",
        "last":"",
        "form":"V",
        "hometown":"Barre, VT",
        "club":false,
        "class":true,
    },
    {
        "name":"Jean",
        "last":"G",
        "form":"V",
        "hometown":"Jersey City, NJ",
        "club":true,
        "class":true,
    },
    {
        "name":"Marlie",
        "last":"R",
        "form":"VI",
        "hometown":"Atlanta, GA",
        "club":false,
        "class":true,
    },
    {
        "name":"Tess",
        "last":"B",
        "form":"IV",
        "hometown":"Northampton, MA",
        "club":true,
        "class":true,
    },
    {
        "name":"Mikey",
        "last":"W Jr.",
        "form":"V",
        "hometown":"Philadelphia, PA",
        "club":true,
        "class":false,
    },
];
